# Generated by Django 5.2.17 on 2026-08-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppInboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('wa_id', models.CharField(db_index=True, max_length=32, verbose_name="numéro de l'expéditeur")),
                ('profile_name', models.CharField(blank=True, max_length=255)),
                ('message_type', models.CharField(choices=[('text', 'Texte'), ('image', 'Image'), ('video', 'Vidéo'), ('audio', 'Audio'), ('document', 'Document'), ('sticker', 'Sticker'), ('location', 'Localisation'), ('contacts', 'Contacts'), ('button', 'Bouton'), ('interactive', 'Interactif'), ('unknown', 'Inconnu')], default='unknown', max_length=20)),
                ('body', models.TextField(blank=True)),
                ('media_id', models.CharField(blank=True, max_length=255)),
                ('from_me', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField()),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'message WhatsApp entrant',
                'verbose_name_plural': 'messages WhatsApp entrants',
                'ordering': ('-sent_at',),
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessageStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('sent', 'Envoyé'), ('delivered', 'Délivré'), ('read', 'Lu'), ('failed', 'Échec')], max_length=16)),
                ('status_timestamp', models.CharField(blank=True, max_length=32)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'statut WhatsApp',
                'verbose_name_plural': 'statuts WhatsApp',
                'ordering': ('-received_at',),
                'constraints': [models.UniqueConstraint(fields=('message_id', 'status'), name='one_whatsapp_status_per_message')],
            },
        ),
    ]
