# Generated by Django 5.2.16 on 2026-07-21 16:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def mark_existing_phones_as_verified(apps, schema_editor):
    user_model = apps.get_model("accounts", "User")
    user_model.objects.filter(phone_verified_at__isnull=True).update(
        phone_verified_at=timezone.now()
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountOtpChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('PHONE_VERIFICATION', 'Verification du telephone'), ('PASSWORD_RESET', 'Reinitialisation du mot de passe')], max_length=24)),
                ('destination', models.CharField(max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_otp_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'purpose', 'created_at'], name='account_otp_lookup_idx')],
            },
        ),
        migrations.RunPython(mark_existing_phones_as_verified, migrations.RunPython.noop),
    ]
