# Generated by Django 5.2.16 on 2026-07-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accountotpchallenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountotpchallenge',
            name='channel',
            field=models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email')], default='SMS', max_length=8),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accountotpchallenge',
            name='destination',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='accountotpchallenge',
            name='purpose',
            field=models.CharField(choices=[('PHONE_VERIFICATION', 'Verification du telephone'), ('EMAIL_VERIFICATION', "Verification de l'email"), ('PASSWORD_RESET', 'Reinitialisation du mot de passe')], max_length=24),
        ),
    ]
