# Generated by Django 5.2.16 on 2026-07-24 12:51

import modules.accounts.phones
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accountotpchallenge_channel_user_email_verified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[modules.accounts.phones.validate_e164], verbose_name='telephone'),
        ),
    ]
