# Generated by Django 5.2.17 on 2026-08-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_currency',
            field=models.CharField(blank=True, choices=[('XOF', 'Franc CFA (UEMOA)'), ('XAF', 'Franc CFA (CEMAC)'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('MAD', 'Moroccan Dirham'), ('NGN', 'Nigerian Naira'), ('KES', 'Kenyan Shilling'), ('GHS', 'Ghanaian Cedi'), ('ZAR', 'South African Rand')], default='', help_text='Devise ISO 4217. Laisser vide pour la devise par defaut.', max_length=3, verbose_name='devise preferee'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_date_format',
            field=models.CharField(blank=True, choices=[('dmy', 'JJ/MM/AAAA'), ('mdy', 'MM/JJ/AAAA'), ('ymd', 'AAAA-MM-JJ')], default='', max_length=8, verbose_name='format de date prefere'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('fr', 'Français'), ('en', 'English'), ('es', 'Español'), ('pt', 'Português'), ('ar', 'العربية'), ('sw', 'Kiswahili'), ('bm', 'Bamanankan'), ('wo', 'Wolof'), ('ln', 'Lingála'), ('yo', 'Yorùbá'), ('ha', 'Hausa'), ('am', 'አማርኛ')], default='', help_text='Laisser vide pour la detection automatique.', max_length=10, verbose_name='langue preferee'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_number_format',
            field=models.CharField(blank=True, choices=[('fr', '1 234 567,89'), ('en', '1,234,567.89')], default='', max_length=8, verbose_name='format de nombre prefere'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_timezone',
            field=models.CharField(blank=True, default='', help_text='Code IANA, ex. Africa/Abidjan. Laisser vide pour le defaut.', max_length=64, verbose_name='fuseau horaire prefere'),
        ),
    ]
