# Generated by Django 5.2.17 on 2026-08-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_preferred_currency_user_preferred_date_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_currency',
            field=models.CharField(blank=True, choices=[('XOF', 'Franc CFA (UEMOA)'), ('XAF', 'Franc CFA (CEMAC)'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('MAD', 'Moroccan Dirham'), ('NGN', 'Nigerian Naira'), ('KES', 'Kenyan Shilling'), ('GHS', 'Ghanaian Cedi'), ('ZAR', 'South African Rand'), ('CDF', 'Congolese Franc')], default='', help_text='Devise ISO 4217. Laisser vide pour la devise par defaut.', max_length=3, verbose_name='devise preferee'),
        ),
    ]
