# Generated by Django 5.2.17 on 2026-08-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_preferred_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur ImmoLib'), ('USER', 'Utilisateur')], default='USER', help_text="Role systeme. Seul le role ADMIN ouvre l'espace d'administration. Le statut bailleur ou locataire reste derive des donnees.", max_length=16, verbose_name='role'),
        ),
    ]
