# Generated by Django 5.2.17 on 2026-08-07 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ex. XOF, USD, EUR, MAD, NGN, KES, GHS, ZAR.', max_length=3, unique=True, verbose_name='code ISO 4217')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('symbol', models.CharField(blank=True, max_length=16, verbose_name='symbole')),
                ('decimals', models.PositiveSmallIntegerField(default=2, verbose_name='decimales')),
                ('symbol_position', models.CharField(choices=[('prefix', 'Avant le montant'), ('suffix', 'Après le montant')], default='suffix', max_length=8, verbose_name='position du symbole')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
            ],
            options={
                'verbose_name': 'devise',
                'verbose_name_plural': 'devises',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code ISO 639-1, ex. fr, en, es, pt, ar.', max_length=10, unique=True, verbose_name='code')),
                ('native_name', models.CharField(max_length=100, verbose_name='nom natif')),
                ('english_name', models.CharField(blank=True, max_length=100, verbose_name='nom anglais')),
                ('is_active', models.BooleanField(default=True, help_text='Une langue inactive ne peut jamais etre servie.', verbose_name='active')),
                ('is_default', models.BooleanField(default=False, help_text="Utilisee lorsque aucune preference n'est exprimable.", verbose_name='langue par defaut')),
                ('is_rtl', models.BooleanField(default=False, help_text="Coche pour l'arabe et autres ecritures RTL.", verbose_name='ecriture droite a gauche')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
            ],
            options={
                'verbose_name': 'langue',
                'verbose_name_plural': 'langues',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ex. CI, FR, US, MA, NG, KE, GH, ZA.', max_length=2, unique=True, verbose_name='code ISO 3166-1')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('default_timezone', models.CharField(blank=True, help_text='Code IANA, ex. Africa/Abidjan.', max_length=64, verbose_name='fuseau par defaut')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='countries', to='i18n.currency', verbose_name='devise')),
            ],
            options={
                'verbose_name': 'pays',
                'verbose_name_plural': 'pays',
                'ordering': ['order', 'code'],
            },
        ),
    ]
