# Generated by Django 5.2.16 on 2026-07-21 12:13

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_rentcharge_amount_paid_and_more'),
        ('leases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='montant')),
                ('currency', models.CharField(default='XOF', max_length=3, verbose_name='devise')),
                ('method', models.CharField(choices=[('CASH', 'Especes'), ('BANK_TRANSFER', 'Virement bancaire'), ('EXTERNAL_MOBILE_MONEY', 'Mobile Money hors ImmoLib'), ('OTHER', 'Autre')], max_length=32, verbose_name='moyen')),
                ('status', models.CharField(choices=[('RECORDED_BY_OWNER', 'Declare par le bailleur'), ('CONFIRMED_BY_TENANT', 'Confirme par le locataire'), ('DISPUTED_BY_TENANT', 'Conteste par le locataire'), ('CANCELLED', 'Annule')], default='RECORDED_BY_OWNER', max_length=32, verbose_name='statut')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='recu le')),
                ('external_reference', models.CharField(blank=True, max_length=120, verbose_name='reference externe')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('idempotency_key', models.UUIDField(verbose_name="cle d'idempotence")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_payments', to=settings.AUTH_USER_MODEL, verbose_name='enregistre par')),
            ],
            options={
                'verbose_name': 'paiement',
                'verbose_name_plural': 'paiements',
                'ordering': ['-received_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='montant affecte')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='payments.payment', verbose_name='paiement')),
                ('rent_charge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='billing.rentcharge', verbose_name='echeance')),
            ],
            options={
                'verbose_name': 'affectation de paiement',
                'verbose_name_plural': 'affectations de paiement',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='rent_charges',
            field=models.ManyToManyField(related_name='payments', through='payments.PaymentAllocation', to='billing.rentcharge'),
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('RECORDED', 'Paiement enregistre'), ('TENANT_CONFIRMED', 'Locataire a confirme'), ('TENANT_DISPUTED', 'Locataire a conteste'), ('CANCELLED', 'Paiement annule')], max_length=32, verbose_name='type')),
                ('reason', models.TextField(blank=True, verbose_name='motif')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_events', to='leases.tenant', verbose_name='locataire acteur')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_events', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur acteur')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='payments.payment', verbose_name='paiement')),
            ],
            options={
                'verbose_name': 'evenement de paiement',
                'verbose_name_plural': 'evenements de paiement',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.UniqueConstraint(fields=('payment', 'rent_charge'), name='one_allocation_per_payment_and_charge'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_allocation_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('recorded_by', 'idempotency_key'), name='one_payment_per_recorder_idempotency_key'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_positive'),
        ),
    ]
