# Generated by Django 5.2.16 on 2026-07-23 14:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Especes'), ('BANK_TRANSFER', 'Virement bancaire'), ('MOBILE_MONEY', 'Mobile Money confirmé'), ('EXTERNAL_MOBILE_MONEY', 'Mobile Money hors ImmoLib'), ('OTHER', 'Autre')], max_length=32, verbose_name='moyen'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('RECORDED_BY_OWNER', 'Declare par le bailleur'), ('CONFIRMED_BY_PROVIDER', 'Confirmé par le prestataire'), ('CONFIRMED_BY_TENANT', 'Confirme par le locataire'), ('DISPUTED_BY_TENANT', 'Conteste par le locataire'), ('CANCELLED', 'Annule')], default='RECORDED_BY_OWNER', max_length=32, verbose_name='statut'),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='event_type',
            field=models.CharField(choices=[('RECORDED', 'Paiement enregistre'), ('PROVIDER_CONFIRMED', 'Prestataire a confirme'), ('TENANT_CONFIRMED', 'Locataire a confirme'), ('TENANT_DISPUTED', 'Locataire a conteste'), ('CANCELLED', 'Paiement annule')], max_length=32, verbose_name='type'),
        ),
        migrations.CreateModel(
            name='PaymentProviderEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=40)),
                ('external_event_id', models.CharField(max_length=120)),
                ('event_type', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('RECEIVED', 'Reçu'), ('PROCESSED', 'Traité'), ('IGNORED', 'Ignoré'), ('FAILED', 'Échec')], default='RECEIVED', max_length=12)),
                ('transaction_reference', models.CharField(blank=True, max_length=120)),
                ('rent_charge_reference', models.CharField(blank=True, max_length=64)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payload_digest', models.CharField(max_length=64)),
                ('failure_reason', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider_events', to='payments.payment')),
            ],
            options={
                'verbose_name': 'événement prestataire de paiement',
                'verbose_name_plural': 'événements prestataire de paiement',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['status', 'received_at'], name='payment_provider_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'external_event_id'), name='one_payment_provider_event')],
            },
        ),
    ]
