# Generated by Django 5.2.16 on 2026-07-24 12:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_rentcharge_amount_released_and_more'),
        ('payments', '0002_alter_payment_method_alter_payment_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityDepositMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('REFUND', 'Remboursement'), ('RETENTION', 'Retenue justifiée'), ('APPLY_TO_RENT', 'Affectation au loyer')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('reason', models.TextField(blank=True)),
                ('agreement_confirmed', models.BooleanField(default=False)),
                ('agreement_reference', models.CharField(blank=True, max_length=160)),
                ('idempotency_key', models.UUIDField()),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-occurred_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='is_cash_movement',
            field=models.BooleanField(default=True, help_text="Faux lorsqu'une caution déjà encaissée est affectée à un loyer.", verbose_name='mouvement de trésorerie'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Especes'), ('BANK_TRANSFER', 'Virement bancaire'), ('MOBILE_MONEY', 'Mobile Money confirmé'), ('EXTERNAL_MOBILE_MONEY', 'Mobile Money hors ImmoLib'), ('SECURITY_DEPOSIT_APPLICATION', 'Caution affectée au loyer'), ('OTHER', 'Autre')], max_length=32, verbose_name='moyen'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'received_at'], name='payment_status_received_idx'),
        ),
        migrations.AddField(
            model_name='securitydepositmovement',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='security_deposit_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securitydepositmovement',
            name='deposit_obligation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='security_deposit_movements', to='billing.rentcharge'),
        ),
        migrations.AddField(
            model_name='securitydepositmovement',
            name='resulting_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='security_deposit_movements', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='securitydepositmovement',
            name='target_rent_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_deposit_movements', to='billing.rentcharge'),
        ),
        migrations.AddConstraint(
            model_name='securitydepositmovement',
            constraint=models.UniqueConstraint(fields=('created_by', 'idempotency_key'), name='one_deposit_movement_per_actor_key'),
        ),
        migrations.AddConstraint(
            model_name='securitydepositmovement',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='security_deposit_movement_positive'),
        ),
        migrations.AddConstraint(
            model_name='securitydepositmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('agreement_confirmed', True), ('movement_type', 'APPLY_TO_RENT'), ('target_rent_charge__isnull', False)), models.Q(('movement_type__in', ('REFUND', 'RETENTION')), ('target_rent_charge__isnull', True)), _connector='OR'), name='deposit_movement_target_matches_type'),
        ),
    ]
