# Generated by Django 5.2.17 on 2026-08-08 08:48

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_rentcharge_amount_released_and_more'),
        ('payments', '0003_securitydepositmovement_payment_is_cash_movement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethodAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operator', models.CharField(choices=[('MTN_MOMO', 'MTN Mobile Money'), ('ORANGE_MONEY', 'Orange Money'), ('MOOV_MONEY', 'Moov Money'), ('WAVE', 'Wave'), ('BANK_TRANSFER', 'Virement bancaire'), ('CASH', 'Espèces'), ('OTHER', 'Autre')], max_length=32, verbose_name='opérateur')),
                ('account_identifier', models.CharField(max_length=120, verbose_name='identifiant du compte')),
                ('account_holder', models.CharField(blank=True, max_length=120, verbose_name='titulaire')),
                ('is_default', models.BooleanField(default=False, verbose_name='compte par défaut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_method_accounts', to=settings.AUTH_USER_MODEL, verbose_name='bailleur')),
            ],
            options={
                'verbose_name': 'compte de paiement',
                'verbose_name_plural': 'comptes de paiement',
                'ordering': ['-is_default', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=24, unique=True, verbose_name='référence')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='montant demandé')),
                ('amount_received', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='montant reçu')),
                ('currency', models.CharField(default='XOF', max_length=3, verbose_name='devise')),
                ('operator', models.CharField(choices=[('MTN_MOMO', 'MTN Mobile Money'), ('ORANGE_MONEY', 'Orange Money'), ('MOOV_MONEY', 'Moov Money'), ('WAVE', 'Wave'), ('BANK_TRANSFER', 'Virement bancaire'), ('CASH', 'Espèces'), ('OTHER', 'Autre')], max_length=32, verbose_name='moyen')),
                ('payee_name', models.CharField(blank=True, max_length=160, verbose_name='nom du bénéficiaire')),
                ('payee_phone', models.CharField(blank=True, max_length=20, verbose_name='téléphone du bénéficiaire')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmé'), ('NOT_RECEIVED', 'Non reçu'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=16, verbose_name='statut')),
                ('note', models.TextField(blank=True, verbose_name='note du locataire')),
                ('processing_note', models.TextField(blank=True, verbose_name='note de traitement')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='traité le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_requests', to='payments.paymentmethodaccount', verbose_name='compte de réception')),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_payment_requests', to=settings.AUTH_USER_MODEL, verbose_name='bailleur bénéficiaire')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_request', to='payments.payment', verbose_name='paiement créé')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processed_payment_requests', to=settings.AUTH_USER_MODEL, verbose_name='traité par')),
                ('rent_charge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_requests', to='billing.rentcharge', verbose_name='échéance')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_payment_requests', to=settings.AUTH_USER_MODEL, verbose_name='initié par')),
            ],
            options={
                'verbose_name': 'demande de paiement',
                'verbose_name_plural': 'demandes de paiement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='paymentmethodaccount',
            constraint=models.UniqueConstraint(fields=('owner', 'operator', 'account_identifier'), name='one_method_account_per_owner_operator_identifier'),
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['status', 'created_at'], name='payment_request_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentrequest',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_request_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymentrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('rent_charge',), name='one_pending_payment_request_per_charge'),
        ),
    ]
