# Generated by Django 5.2.17 on 2026-08-27 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_rentcharge_amount_released_and_more'),
        ('payments', '0004_paymentmethodaccount_paymentrequest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentproviderevent',
            name='payment_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider_events', to='payments.paymentrequest', verbose_name='demande liée'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='expire le'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='external_transaction_id',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='transaction externe'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='failure_reason',
            field=models.TextField(blank=True, default='', verbose_name="raison d'échec"),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='provider',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='prestataire'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='provider_reference',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='référence prestataire'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='provider_status',
            field=models.CharField(blank=True, default='', max_length=24, verbose_name='statut prestataire'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Especes'), ('BANK_TRANSFER', 'Virement bancaire'), ('MOBILE_MONEY', 'Mobile Money confirmé'), ('EXTERNAL_MOBILE_MONEY', 'Mobile Money hors ImmoLib'), ('PI_SPI', 'PI-SPI (BCEAO)'), ('SECURITY_DEPOSIT_APPLICATION', 'Caution affectée au loyer'), ('OTHER', 'Autre')], max_length=32, verbose_name='moyen'),
        ),
        migrations.AlterField(
            model_name='paymentmethodaccount',
            name='operator',
            field=models.CharField(choices=[('MTN_MOMO', 'MTN Mobile Money'), ('ORANGE_MONEY', 'Orange Money'), ('MOOV_MONEY', 'Moov Money'), ('WAVE', 'Wave'), ('BANK_TRANSFER', 'Virement bancaire'), ('PI_SPI', 'PI-SPI (BCEAO)'), ('CASH', 'Espèces'), ('OTHER', 'Autre')], max_length=32, verbose_name='opérateur'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='operator',
            field=models.CharField(choices=[('MTN_MOMO', 'MTN Mobile Money'), ('ORANGE_MONEY', 'Orange Money'), ('MOOV_MONEY', 'Moov Money'), ('WAVE', 'Wave'), ('BANK_TRANSFER', 'Virement bancaire'), ('PI_SPI', 'PI-SPI (BCEAO)'), ('CASH', 'Espèces'), ('OTHER', 'Autre')], max_length=32, verbose_name='moyen'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('PROCESSING', 'En cours'), ('CONFIRMED', 'Confirmé'), ('NOT_RECEIVED', 'Non reçu'), ('CANCELLED', 'Annulé'), ('FAILED', 'Échoué'), ('EXPIRED', 'Expiré')], default='PENDING', max_length=16, verbose_name='statut'),
        ),
        migrations.AddConstraint(
            model_name='paymentrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PROCESSING')), fields=('rent_charge',), name='one_processing_payment_request_per_charge'),
        ),
    ]
