# Generated by Django 5.2.17 on 2026-08-27 12:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_rentcharge_amount_released_and_more'),
        ('payments', '0005_add_pi_spi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paymentrequest',
            name='one_processing_payment_request_per_charge',
        ),
        migrations.AddConstraint(
            model_name='paymentrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'PROCESSING'])), fields=('rent_charge',), name='one_active_payment_request_per_charge'),
        ),
    ]
