# Generated by Django 5.2.16 on 2026-07-21 12:20

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_rentcharge_amount_paid_and_more'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAccessLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_document_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OtpChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(max_length=16)),
                ('destination', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='otp_challenges', to='documents.documentaccesslink')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=40, unique=True, verbose_name='reference')),
                ('document_type', models.CharField(choices=[('PAYMENT_RECEIPT', 'Recu de paiement'), ('RENT_RECEIPT', 'Quittance de loyer')], max_length=24, verbose_name='type')),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('VOIDED', 'Invalide')], default='ACTIVE', max_length=12, verbose_name='statut')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='montant documente')),
                ('currency', models.CharField(max_length=3, verbose_name='devise')),
                ('period_start', models.DateField(verbose_name='debut de periode')),
                ('period_end', models.DateField(verbose_name='fin de periode')),
                ('payment_method', models.CharField(blank=True, max_length=64, verbose_name='moyen de paiement')),
                ('house_name', models.CharField(max_length=120, verbose_name='maison')),
                ('house_address', models.CharField(max_length=255, verbose_name='adresse de la maison')),
                ('tenant_name', models.CharField(max_length=160, verbose_name='locataire')),
                ('tenant_phone', models.CharField(max_length=20, verbose_name='telephone du locataire')),
                ('tenant_email', models.EmailField(blank=True, max_length=254, verbose_name='email du locataire')),
                ('owner_name', models.CharField(max_length=160, verbose_name='bailleur')),
                ('owner_phone', models.CharField(max_length=20, verbose_name='telephone du bailleur')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rental_documents', to='payments.payment', verbose_name='paiement')),
                ('rent_charge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_documents', to='billing.rentcharge', verbose_name='echeance')),
            ],
            options={
                'verbose_name': 'document locatif',
                'verbose_name_plural': 'documents locatifs',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.AddField(
            model_name='documentaccesslink',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_links', to='documents.rentaldocument'),
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('DOCUMENT_LINK', 'Lien du document'), ('OTP', 'Code de verification')], max_length=20)),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp')], max_length=16)),
                ('destination', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('QUEUED', 'En attente'), ('SENT', 'Envoye'), ('FAILED', 'Echec')], default='QUEUED', max_length=12)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='documents.documentaccesslink')),
                ('otp_challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='documents.otpchallenge')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('kind', 'DOCUMENT_LINK')), fields=('access_link', 'channel'), name='one_document_link_delivery_per_channel'), models.UniqueConstraint(condition=models.Q(('kind', 'OTP')), fields=('otp_challenge', 'channel'), name='one_otp_delivery_per_challenge_channel')],
            },
        ),
        migrations.AddConstraint(
            model_name='rentaldocument',
            constraint=models.UniqueConstraint(condition=models.Q(('document_type', 'PAYMENT_RECEIPT'), ('status', 'ACTIVE')), fields=('payment', 'document_type'), name='one_active_receipt_per_payment'),
        ),
        migrations.AddConstraint(
            model_name='rentaldocument',
            constraint=models.UniqueConstraint(condition=models.Q(('document_type', 'RENT_RECEIPT'), ('status', 'ACTIVE')), fields=('rent_charge', 'document_type'), name='one_active_rent_receipt_per_charge'),
        ),
        migrations.AddConstraint(
            model_name='rentaldocument',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='rental_document_amount_positive'),
        ),
    ]
