# Generated by Django 5.2.16 on 2026-07-21 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_rentcharge_amount_paid_and_more'),
        ('documents', '0002_notificationdelivery_attempt_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationdelivery',
            name='rent_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notification_deliveries', to='billing.rentcharge'),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='scheduled_for',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificationdelivery',
            name='access_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='documents.documentaccesslink'),
        ),
        migrations.AlterField(
            model_name='notificationdelivery',
            name='kind',
            field=models.CharField(choices=[('DOCUMENT_LINK', 'Lien du document'), ('OTP', 'Code de verification'), ('RENT_REMINDER', 'Rappel de loyer')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='notificationdelivery',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'RENT_REMINDER')), fields=('rent_charge', 'channel', 'scheduled_for'), name='one_rent_reminder_per_charge_channel_date'),
        ),
        migrations.AddConstraint(
            model_name='notificationdelivery',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('access_link__isnull', False), ('kind', 'DOCUMENT_LINK'), ('otp_challenge__isnull', True), ('rent_charge__isnull', True), ('scheduled_for__isnull', True)), models.Q(('access_link__isnull', False), ('kind', 'OTP'), ('otp_challenge__isnull', False), ('rent_charge__isnull', True), ('scheduled_for__isnull', True)), models.Q(('access_link__isnull', True), ('kind', 'RENT_REMINDER'), ('otp_challenge__isnull', True), ('rent_charge__isnull', False), ('scheduled_for__isnull', False)), _connector='OR'), name='notification_delivery_source_matches_kind'),
        ),
    ]
