# Generated by Django 5.2.16 on 2026-07-21 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accountotpchallenge'),
        ('billing', '0002_rentcharge_amount_paid_and_more'),
        ('documents', '0003_notificationdelivery_rent_charge_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notificationdelivery',
            name='notification_delivery_source_matches_kind',
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='account_challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='accounts.accountotpchallenge'),
        ),
        migrations.AlterField(
            model_name='notificationdelivery',
            name='kind',
            field=models.CharField(choices=[('DOCUMENT_LINK', 'Lien du document'), ('OTP', "Code d'acces au document"), ('ACCOUNT_OTP', 'Code de verification du compte'), ('RENT_REMINDER', 'Rappel de loyer')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='notificationdelivery',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'ACCOUNT_OTP')), fields=('account_challenge', 'channel'), name='one_account_otp_delivery_per_channel'),
        ),
        migrations.AddConstraint(
            model_name='notificationdelivery',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('access_link__isnull', False), ('account_challenge__isnull', True), ('kind', 'DOCUMENT_LINK'), ('otp_challenge__isnull', True), ('rent_charge__isnull', True), ('scheduled_for__isnull', True)), models.Q(('access_link__isnull', False), ('account_challenge__isnull', True), ('kind', 'OTP'), ('otp_challenge__isnull', False), ('rent_charge__isnull', True), ('scheduled_for__isnull', True)), models.Q(('access_link__isnull', True), ('account_challenge__isnull', False), ('kind', 'ACCOUNT_OTP'), ('otp_challenge__isnull', True), ('rent_charge__isnull', True), ('scheduled_for__isnull', True)), models.Q(('access_link__isnull', True), ('account_challenge__isnull', True), ('kind', 'RENT_REMINDER'), ('otp_challenge__isnull', True), ('rent_charge__isnull', False), ('scheduled_for__isnull', False)), _connector='OR'), name='notification_delivery_source_matches_kind'),
        ),
    ]
