# Generated by Django 5.2.16 on 2026-07-23 13:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_remove_notificationdelivery_notification_delivery_source_matches_kind_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationdelivery',
            name='channel',
            field=models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('PUSH', 'Notification push')], max_length=16),
        ),
        migrations.CreateModel(
            name='ManualShareEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('NATIVE', "Partage de l'appareil"), ('COPY', 'Copie du lien')], max_length=12)),
                ('destination', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_share_events', to='documents.documentaccesslink')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_share_events', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_share_events', to='documents.rentaldocument')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
