# Generated by Django 5.2.16 on 2026-07-23 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accountotpchallenge_channel_user_email_verified_at_and_more'),
        ('billing', '0002_rentcharge_amount_paid_and_more'),
        ('documents', '0005_alter_notificationdelivery_channel_manualshareevent'),
        ('leases', '0002_tenantinvitation_tenantinvitationshareevent_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notificationdelivery',
            name='notification_delivery_source_matches_kind',
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='tenant_invitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notification_deliveries', to='leases.tenantinvitation'),
        ),
        migrations.AlterField(
            model_name='notificationdelivery',
            name='kind',
            field=models.CharField(choices=[('DOCUMENT_LINK', 'Lien du document'), ('OTP', "Code d'acces au document"), ('ACCOUNT_OTP', 'Code de verification du compte'), ('RENT_REMINDER', 'Rappel de loyer'), ('TENANT_INVITATION', 'Invitation du locataire')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='notificationdelivery',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'TENANT_INVITATION')), fields=('tenant_invitation', 'channel'), name='one_tenant_invitation_delivery_per_channel'),
        ),
        migrations.AddConstraint(
            model_name='notificationdelivery',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('access_link__isnull', False), ('account_challenge__isnull', True), ('kind', 'DOCUMENT_LINK'), ('otp_challenge__isnull', True), ('rent_charge__isnull', True), ('scheduled_for__isnull', True), ('tenant_invitation__isnull', True)), models.Q(('access_link__isnull', False), ('account_challenge__isnull', True), ('kind', 'OTP'), ('otp_challenge__isnull', False), ('rent_charge__isnull', True), ('scheduled_for__isnull', True), ('tenant_invitation__isnull', True)), models.Q(('access_link__isnull', True), ('account_challenge__isnull', False), ('kind', 'ACCOUNT_OTP'), ('otp_challenge__isnull', True), ('rent_charge__isnull', True), ('scheduled_for__isnull', True), ('tenant_invitation__isnull', True)), models.Q(('access_link__isnull', True), ('account_challenge__isnull', True), ('kind', 'RENT_REMINDER'), ('otp_challenge__isnull', True), ('rent_charge__isnull', False), ('scheduled_for__isnull', False), ('tenant_invitation__isnull', True)), models.Q(('access_link__isnull', True), ('account_challenge__isnull', True), ('kind', 'TENANT_INVITATION'), ('otp_challenge__isnull', True), ('rent_charge__isnull', True), ('scheduled_for__isnull', True), ('tenant_invitation__isnull', False)), _connector='OR'), name='notification_delivery_source_matches_kind'),
        ),
    ]
