# Generated by Django 5.2.16 on 2026-07-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_remove_rentcharge_one_rent_charge_per_lease_and_period_and_more'),
        ('documents', '0006_remove_notificationdelivery_notification_delivery_source_matches_kind_and_more'),
        ('payments', '0002_alter_payment_method_alter_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentaldocument',
            name='breakdown',
            field=models.JSONField(blank=True, default=list, verbose_name='détail des affectations'),
        ),
        migrations.AlterField(
            model_name='rentaldocument',
            name='document_type',
            field=models.CharField(choices=[('PAYMENT_RECEIPT', 'Recu de paiement'), ('RENT_RECEIPT', 'Quittance de loyer'), ('DEPOSIT_RECEIPT', 'Reçu de caution')], max_length=24, verbose_name='type'),
        ),
        migrations.AddConstraint(
            model_name='rentaldocument',
            constraint=models.UniqueConstraint(condition=models.Q(('document_type', 'DEPOSIT_RECEIPT'), ('status', 'ACTIVE')), fields=('rent_charge', 'document_type'), name='one_active_deposit_receipt_per_obligation'),
        ),
    ]
