# Generated by Django 5.2.16 on 2026-07-24 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_rentcharge_amount_released_and_more'),
        ('documents', '0007_rentaldocument_breakdown_and_more'),
        ('payments', '0003_securitydepositmovement_payment_is_cash_movement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentaldocument',
            name='deposit_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rental_documents', to='payments.securitydepositmovement', verbose_name='mouvement de caution'),
        ),
        migrations.AlterField(
            model_name='rentaldocument',
            name='document_type',
            field=models.CharField(choices=[('PAYMENT_RECEIPT', 'Recu de paiement'), ('RENT_RECEIPT', 'Quittance de loyer'), ('DEPOSIT_RECEIPT', 'Reçu de caution'), ('DEPOSIT_SETTLEMENT', 'Relevé de caution')], max_length=24, verbose_name='type'),
        ),
        migrations.AddIndex(
            model_name='rentaldocument',
            index=models.Index(fields=['status', 'issued_at'], name='rental_doc_status_issued_idx'),
        ),
        migrations.AddConstraint(
            model_name='rentaldocument',
            constraint=models.UniqueConstraint(condition=models.Q(('document_type', 'DEPOSIT_SETTLEMENT'), ('status', 'ACTIVE')), fields=('deposit_movement', 'document_type'), name='one_active_deposit_settlement_per_movement'),
        ),
    ]
