# Generated by Django 5.2.17 on 2026-08-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_rentaldocument_deposit_movement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationdelivery',
            name='language',
            field=models.CharField(blank=True, default='', help_text='Langue figee a la mise en file ; le worker est asynchrone.', max_length=10, verbose_name='langue du destinataire'),
        ),
    ]
