# Generated by Django 5.2.17 on 2026-08-08 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_notificationdelivery_language'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notificationdelivery',
            name='notification_delivery_source_matches_kind',
        ),
    ]
