# Generated by Django 5.2.17 on 2026-08-08 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_preferred_currency'),
        ('billing', '0004_rentcharge_amount_released_and_more'),
        ('documents', '0010_remove_notificationdelivery_notification_delivery_source_matches_kind'),
        ('leases', '0003_alter_tenant_phone'),
        ('payments', '0004_paymentmethodaccount_paymentrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationdelivery',
            name='payment_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notification_deliveries', to='payments.paymentrequest'),
        ),
        migrations.AlterField(
            model_name='notificationdelivery',
            name='kind',
            field=models.CharField(choices=[('DOCUMENT_LINK', 'Lien du document'), ('OTP', "Code d'acces au document"), ('ACCOUNT_OTP', 'Code de verification du compte'), ('RENT_REMINDER', 'Rappel de loyer'), ('TENANT_INVITATION', 'Invitation du locataire'), ('PAYMENT_REQUEST', 'Paiement à confirmer'), ('PAYMENT_CONFIRMED', 'Paiement confirmé')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='notificationdelivery',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('access_link__isnull', False), ('account_challenge__isnull', True), ('kind', 'DOCUMENT_LINK'), ('otp_challenge__isnull', True), ('payment_request__isnull', True), ('rent_charge__isnull', True), ('scheduled_for__isnull', True), ('tenant_invitation__isnull', True)), models.Q(('access_link__isnull', False), ('account_challenge__isnull', True), ('kind', 'OTP'), ('otp_challenge__isnull', False), ('payment_request__isnull', True), ('rent_charge__isnull', True), ('scheduled_for__isnull', True), ('tenant_invitation__isnull', True)), models.Q(('access_link__isnull', True), ('account_challenge__isnull', False), ('kind', 'ACCOUNT_OTP'), ('otp_challenge__isnull', True), ('payment_request__isnull', True), ('rent_charge__isnull', True), ('scheduled_for__isnull', True), ('tenant_invitation__isnull', True)), models.Q(('access_link__isnull', True), ('account_challenge__isnull', True), ('kind', 'RENT_REMINDER'), ('otp_challenge__isnull', True), ('payment_request__isnull', True), ('rent_charge__isnull', False), ('scheduled_for__isnull', False), ('tenant_invitation__isnull', True)), models.Q(('access_link__isnull', True), ('account_challenge__isnull', True), ('kind', 'TENANT_INVITATION'), ('otp_challenge__isnull', True), ('payment_request__isnull', True), ('rent_charge__isnull', True), ('scheduled_for__isnull', True), ('tenant_invitation__isnull', False)), models.Q(('access_link__isnull', True), ('account_challenge__isnull', True), ('kind__in', ('PAYMENT_REQUEST', 'PAYMENT_CONFIRMED')), ('otp_challenge__isnull', True), ('payment_request__isnull', False), ('rent_charge__isnull', False), ('scheduled_for__isnull', True), ('tenant_invitation__isnull', True)), _connector='OR'), name='notification_delivery_source_matches_kind'),
        ),
    ]
