# Generated by Django 5.2.17 on 2026-08-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_notificationdelivery_payment_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationdelivery',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='otpchallenge',
            name='code_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
