# Generated by Django 5.2.17 on 2026-08-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_accountotpchallenge_code_hash_and_more'),
        ('billing', '0004_rentcharge_amount_released_and_more'),
        ('documents', '0012_notificationdelivery_body_and_more'),
        ('leases', '0003_alter_tenant_phone'),
        ('payments', '0004_paymentmethodaccount_paymentrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationdelivery',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='delivery_status',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='segments_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['channel', 'delivery_status'], name='ntf_delivery_status_idx'),
        ),
    ]
