# Generated by Django 5.2.16 on 2026-07-23 14:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leases', '0002_tenantinvitation_tenantinvitationshareevent_and_more'),
        ('properties', '0005_alter_coownerinvitation_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160, verbose_name='titre')),
                ('description', models.TextField(verbose_name='description')),
                ('category', models.CharField(choices=[('PLUMBING', 'Plomberie'), ('ELECTRICITY', 'Électricité'), ('SECURITY', 'Sécurité'), ('ROOF', 'Toiture'), ('STRUCTURE', 'Structure'), ('EQUIPMENT', 'Équipement'), ('OTHER', 'Autre')], max_length=20, verbose_name='catégorie')),
                ('priority', models.CharField(choices=[('LOW', 'Faible'), ('NORMAL', 'Normale'), ('HIGH', 'Élevée'), ('URGENT', 'Urgente')], default='NORMAL', max_length=12, verbose_name='priorité')),
                ('status', models.CharField(choices=[('REPORTED', 'Signalé'), ('ACKNOWLEDGED', 'Pris en compte'), ('IN_PROGRESS', 'Intervention en cours'), ('RESOLVED', 'Résolu par le bailleur'), ('CLOSED', 'Clôturé par le locataire'), ('CANCELLED', 'Annulé')], default='REPORTED', max_length=20, verbose_name='statut')),
                ('occurred_at', models.DateTimeField(blank=True, null=True, verbose_name='constaté le')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_incidents', to='leases.lease', verbose_name='bail')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_incidents', to='properties.property', verbose_name='maison')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_maintenance_incidents', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_incidents', to='leases.tenant', verbose_name='locataire')),
            ],
            options={
                'verbose_name': 'incident de maintenance',
                'verbose_name_plural': 'incidents de maintenance',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('REPORTED', 'Incident signalé'), ('STATUS_CHANGED', 'Statut modifié'), ('COMMENTED', 'Commentaire ajouté')], max_length=20)),
                ('actor_role', models.CharField(choices=[('OWNER', 'Bailleur'), ('TENANT', 'Locataire')], max_length=12)),
                ('from_status', models.CharField(blank=True, choices=[('REPORTED', 'Signalé'), ('ACKNOWLEDGED', 'Pris en compte'), ('IN_PROGRESS', 'Intervention en cours'), ('RESOLVED', 'Résolu par le bailleur'), ('CLOSED', 'Clôturé par le locataire'), ('CANCELLED', 'Annulé')], max_length=20)),
                ('to_status', models.CharField(blank=True, choices=[('REPORTED', 'Signalé'), ('ACKNOWLEDGED', 'Pris en compte'), ('IN_PROGRESS', 'Intervention en cours'), ('RESOLVED', 'Résolu par le bailleur'), ('CLOSED', 'Clôturé par le locataire'), ('CANCELLED', 'Annulé')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_events', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='maintenance.maintenanceincident')),
            ],
            options={
                'verbose_name': 'événement de maintenance',
                'verbose_name_plural': 'événements de maintenance',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='maintenanceincident',
            index=models.Index(fields=['property', 'status', 'priority'], name='maint_property_status_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceincident',
            index=models.Index(fields=['tenant', 'created_at'], name='maintenance_tenant_date_idx'),
        ),
    ]
