# Generated by Django 5.2.17 on 2026-08-11 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
        ('properties', '0007_alter_property_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceincident',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_incidents', to='properties.property', verbose_name='bien'),
        ),
    ]
