# Generated by Django 5.2.17 on 2026-08-11 14:35

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0013_notificationdelivery_delivered_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsDeliveryReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_message_id', models.CharField(db_index=True, max_length=160, verbose_name='identifiant Orange')),
                ('delivery_status', models.CharField(max_length=32, verbose_name='statut Orange')),
                ('address', models.CharField(blank=True, max_length=20, verbose_name='destinataire')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='payload brut')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'accuse de reception SMS',
                'verbose_name_plural': 'accuses de reception SMS',
                'ordering': ['-received_at'],
                'constraints': [models.UniqueConstraint(fields=('provider_message_id', 'delivery_status'), name='one_sms_dr_per_message_status')],
            },
        ),
        migrations.CreateModel(
            name='SmsSendRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_message_id', models.CharField(max_length=160, unique=True, verbose_name='identifiant Orange')),
                ('recipient', models.CharField(max_length=20, verbose_name='destinataire')),
                ('segments_count', models.PositiveSmallIntegerField(default=1, verbose_name='segments')),
                ('estimated_cost_xof', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='cout estime (FCFA)')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sms_send_records', to='documents.notificationdelivery', verbose_name='message en file')),
            ],
            options={
                'verbose_name': 'SMS envoye',
                'verbose_name_plural': 'SMS envoyes',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['sent_at', 'segments_count'], name='sms_send_record_stats_idx')],
            },
        ),
    ]
