# Generated by Django 5.2.17 on 2026-08-08 18:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('price_monthly', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('max_houses', models.PositiveSmallIntegerField(default=1)),
                ('features', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('PENDING', 'En attente'), ('EXPIRED', 'Expiré'), ('CANCELLED', 'Annulé')], default='ACTIVE', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField()),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SUCCESSFUL', 'Réussi'), ('FAILED', 'Échoué'), ('CANCELLED', 'Annulé'), ('EXPIRED', 'Expiré')], default='PENDING', max_length=16)),
                ('provider', models.CharField(choices=[('MANUAL', 'Activation manuelle (pilote)'), ('PAYDUNYA', 'PayDunya')], default='PAYDUNYA', max_length=16)),
                ('provider_reference', models.CharField(blank=True, default='', max_length=120)),
                ('provider_hash', models.CharField(blank=True, default='', max_length=255)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='subscriptions.subscriptionplan')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='subscriptions.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'expires_at'], name='sub_status_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'status'], name='sub_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptiontransaction',
            index=models.Index(fields=['provider_reference'], name='sub_txn_provider_ref_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptiontransaction',
            index=models.Index(fields=['user', 'status'], name='sub_txn_user_status_idx'),
        ),
    ]
