# Generated by Django 5.2.17 on 2026-08-09 08:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('ADMIN_LOGIN', 'Connexion admin'), ('USER_SUSPENDED', 'Utilisateur suspendu'), ('USER_REACTIVATED', 'Utilisateur reactive'), ('USER_ROLE_CHANGED', 'Role utilisateur modifie'), ('SUBSCRIPTION_CHANGED', 'Abonnement modifie'), ('SUBSCRIPTION_CANCELLED', 'Abonnement annule'), ('SUBSCRIPTION_EXTENDED', 'Abonnement prolonge'), ('SUBSCRIPTION_ACTIVATED', 'Abonnement active')], max_length=32)),
                ('target_type', models.CharField(blank=True, default='', max_length=64)),
                ('target_id', models.CharField(blank=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='administrateur')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin', 'created_at'], name='audit_admin_date_idx'), models.Index(fields=['action', 'created_at'], name='audit_action_date_idx')],
            },
        ),
    ]
