# Generated by Django 5.2.16 on 2026-07-21 11:44

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0002_alter_ownership_ownership_percentage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=160, verbose_name='nom complet')),
                ('phone', models.CharField(max_length=20, verbose_name='telephone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('status', models.CharField(choices=[('UNREGISTERED', 'Sans compte ImmoLib'), ('INVITED', 'Invite'), ('ACTIVE', 'Compte active'), ('BLOCKED', 'Bloque')], default='UNREGISTERED', max_length=20, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tenants', to=settings.AUTH_USER_MODEL, verbose_name='cree par')),
                ('linked_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_profiles', to=settings.AUTH_USER_MODEL, verbose_name='compte ImmoLib')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='properties.property', verbose_name='maison')),
            ],
            options={
                'verbose_name': 'locataire',
                'verbose_name_plural': 'locataires',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('ACTIVE', 'Actif'), ('ENDED', 'Termine'), ('CANCELLED', 'Annule')], default='DRAFT', max_length=20, verbose_name='statut')),
                ('start_date', models.DateField(verbose_name='date de debut')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='date de fin')),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='loyer mensuel')),
                ('monthly_charges', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='charges mensuelles')),
                ('due_day', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)], verbose_name='jour limite de paiement')),
                ('security_deposit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='caution')),
                ('rent_advance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='avance sur loyer')),
                ('currency', models.CharField(default='XOF', max_length=3, verbose_name='devise')),
                ('accepts_mobile_money', models.BooleanField(default=True)),
                ('accepts_cash', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_leases', to=settings.AUTH_USER_MODEL, verbose_name='cree par')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='properties.property', verbose_name='maison')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='leases.tenant', verbose_name='locataire')),
            ],
            options={
                'verbose_name': 'bail',
                'verbose_name_plural': 'baux',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.UniqueConstraint(fields=('property', 'phone'), name='one_tenant_phone_per_property'),
        ),
        migrations.AddConstraint(
            model_name='lease',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('property',), name='one_active_lease_per_property'),
        ),
        migrations.AddConstraint(
            model_name='lease',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='lease_end_on_or_after_start'),
        ),
        migrations.AddConstraint(
            model_name='lease',
            constraint=models.CheckConstraint(condition=models.Q(('monthly_rent__gt', 0)), name='lease_monthly_rent_positive'),
        ),
        migrations.AddConstraint(
            model_name='lease',
            constraint=models.CheckConstraint(condition=models.Q(('monthly_charges__gte', 0)), name='lease_monthly_charges_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='lease',
            constraint=models.CheckConstraint(condition=models.Q(('security_deposit__gte', 0)), name='lease_security_deposit_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='lease',
            constraint=models.CheckConstraint(condition=models.Q(('rent_advance__gte', 0)), name='lease_rent_advance_non_negative'),
        ),
    ]
