# Generated by Django 5.2.16 on 2026-07-23 14:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('ACCEPTED', 'Acceptée'), ('REVOKED', 'Révoquée'), ('EXPIRED', 'Expirée')], default='PENDING', max_length=12)),
                ('expires_at', models.DateTimeField()),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_tenant_invitations', to=settings.AUTH_USER_MODEL)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claimed_tenant_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_tenant_invitations', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitations', to='leases.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantInvitationShareEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('NATIVE', "Partage de l'appareil"), ('COPY', 'Copie du message')], max_length=12)),
                ('destination', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_invitation_share_events', to=settings.AUTH_USER_MODEL)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='share_events', to='leases.tenantinvitation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tenantinvitation',
            index=models.Index(fields=['status', 'expires_at'], name='tenant_invitation_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenantinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('tenant',), name='one_pending_invitation_per_tenant'),
        ),
    ]
