"""Enveloppe les dernieres chaines FR dans gettext (gettext_lazy) sur les modules.

Chaque entree est (chemin, ancien, nouveau, [attendu]). ``attendu`` est le
nombre d'occurrences prevu (defaut 1). Le script ecrit les fichiers UTF-8.
"""
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent / "modules"

REPLACEMENTS = [
    # ---- payments/services.py ----
    ("payments/services.py",
     '"Un paiement ne peut pas être réparti entre plusieurs baux."',
     '_("Un paiement ne peut pas être réparti entre plusieurs baux.")'),
    ("payments/services.py",
     '"Le montant du paiement doit être égal à la somme des affectations."',
     '_("Le montant du paiement doit être égal à la somme des affectations.")'),
    ("payments/services.py",
     '                "Le montant affecte a "\n'
     '                f"{item.charge.obligation_label} depasse le solde restant de "\n'
     '                f"{outstanding} {item.charge.currency}."',
     '                _("Le montant affecte a {label} depasse le solde restant de "\n'
     '                  "{outstanding} {currency}.").format(\n'
     '                    label=item.charge.obligation_label,\n'
     '                    outstanding=outstanding,\n'
     '                    currency=item.charge.currency,\n'
     '                )'),
    ("payments/services.py",
     '"Ce paiement a été confirmé par le prestataire Mobile Money."',
     '_("Ce paiement a été confirmé par le prestataire Mobile Money.")'),
    ("payments/services.py",
     '"Une affectation de caution ne s\'annule pas comme un encaissement. "\n'
     '            "Consultez le journal de caution."',
     '_("Une affectation de caution ne s\'annule pas comme un encaissement. "\n'
     '            "Consultez le journal de caution.")'),
    ("payments/services.py",
     '"Un paiement confirmé par le prestataire ne peut pas être annulé manuellement."',
     '_("Un paiement confirmé par le prestataire ne peut pas être annulé manuellement.")'),
    ("payments/services.py",
     '"Ce versement de caution ne peut plus être annulé car une partie "\n'
     '                "de la caution a déjà été libérée."',
     '_("Ce versement de caution ne peut plus être annulé car une partie "\n'
     '                "de la caution a déjà été libérée.")'),
    ("payments/services.py",
     '"Cette clé d\'idempotence a déjà servi avec des données différentes."',
     '_("Cette clé d\'idempotence a déjà servi avec des données différentes.")',
     2),
    ("payments/services.py",
     '"Le montant dépasse la caution encore détenue de "\n'
     '            f"{deposit.held_balance} {deposit.currency}."',
     '_("Le montant dépasse la caution encore détenue de "\n'
     '            "{held_balance} {currency}.").format(\n'
     '                held_balance=deposit.held_balance, currency=deposit.currency\n'
     '            )'),
    ("payments/services.py",
     '"L\'accord du locataire et sa référence sont obligatoires."',
     '_("L\'accord du locataire et sa référence sont obligatoires.")'),
    ("payments/services.py",
     '"La caution peut seulement être affectée à un loyer du même bail."',
     '_("La caution peut seulement être affectée à un loyer du même bail.")'),
    ("payments/services.py",
     'f"Le montant dépasse le solde du loyer de {outstanding} "\n'
     '                f"{target.currency}."',
     '_("Le montant dépasse le solde du loyer de {outstanding} "\n'
     '                "{currency}.").format(outstanding=outstanding, currency=target.currency)'),
    ("payments/services.py",
     'note=reason or "Affectation de la caution au loyer"',
     'note=reason or _("Affectation de la caution au loyer")'),
    ("payments/services.py",
     '"Cet identifiant d\'événement a déjà été utilisé avec un autre contenu."',
     '_("Cet identifiant d\'événement a déjà été utilisé avec un autre contenu.")'),
    ("payments/services.py",
     '"Le montant Mobile Money doit être strictement positif."',
     '_("Le montant Mobile Money doit être strictement positif.")'),
    ("payments/services.py",
     'f"Le montant dépasse le solde restant de {outstanding} {charge.currency}."',
     '_("Le montant dépasse le solde restant de {outstanding} {currency}.").format(\n'
     '                        outstanding=outstanding, currency=charge.currency\n'
     '                    )'),
    ("payments/services.py",
     '"Échéance inconnue."',
     '_("Échéance inconnue.")'),
    ("payments/services.py",
     '"La caution ne se règle pas par demande de paiement."',
     '_("La caution ne se règle pas par demande de paiement.")'),
    ("payments/services.py",
     '"Une demande est déjà en attente pour cette échéance."',
     '_("Une demande est déjà en attente pour cette échéance.")'),
    ("payments/services.py",
     '"Ce compte de réception n\'appartient pas au bailleur du bien."',
     '_("Ce compte de réception n\'appartient pas au bailleur du bien.")'),
    ("payments/services.py",
     '"Le compte choisi ne correspond pas au moyen de paiement."',
     '_("Le compte choisi ne correspond pas au moyen de paiement.")'),
    ("payments/services.py",
     'f"Le montant reçu dépasse le solde restant de {outstanding} "\n'
     '            f"{charge.currency}."',
     '_("Le montant reçu dépasse le solde restant de {outstanding} "\n'
     '            "{currency}.").format(outstanding=outstanding, currency=charge.currency)'),
    ("payments/services.py",
     '"Cette cle d\'idempotence a deja servi avec des donnees differentes."',
     '_("Cette cle d\'idempotence a deja servi avec des donnees differentes.")'),
    ("payments/services.py",
     '"Chaque montant affecté doit être strictement positif."',
     '_("Chaque montant affecté doit être strictement positif.")'),
    ("payments/services.py",
     '"Une obligation annulée ne peut pas recevoir de paiement."',
     '_("Une obligation annulée ne peut pas recevoir de paiement.")'),
    ("payments/services.py",
     'raise ValidationError("Une échéance annulée ne peut pas recevoir de paiement.")',
     'raise ValidationError(_("Une échéance annulée ne peut pas recevoir de paiement."))'),

    # ---- payments/models.py ----
    ("payments/models.py",
     '"Especes"',
     '_("Especes")', 2),
    ("payments/models.py",
     '"Virement bancaire"',
     '_("Virement bancaire")'),
    ("payments/models.py",
     '"Mobile Money confirmé"',
     '_("Mobile Money confirmé")'),
    ("payments/models.py",
     '"Mobile Money hors ImmoLib"',
     '_("Mobile Money hors ImmoLib")'),
    ("payments/models.py",
     '"Caution affectée au loyer"',
     '_("Caution affectée au loyer")'),
    ("payments/models.py",
     '"Autre"',
     '_("Autre")'),
    ("payments/models.py",
     '"Declare par le bailleur"',
     '_("Declare par le bailleur")'),
    ("payments/models.py",
     '"Confirmé par le prestataire"',
     '_("Confirmé par le prestataire")'),
    ("payments/models.py",
     '"Confirme par le locataire"',
     '_("Confirme par le locataire")'),
    ("payments/models.py",
     '"Conteste par le locataire"',
     '_("Conteste par le locataire")'),
    ("payments/models.py",
     '"Annule"',
     '_("Annule")'),
    ("payments/models.py",
     '"Remboursement"',
     '_("Remboursement")'),
    ("payments/models.py",
     '"Retenue justifiée"',
     '_("Retenue justifiée")'),
    ("payments/models.py",
     '"Affectation au loyer"',
     '_("Affectation au loyer")'),
    ("payments/models.py",
     '"Traité"',
     '_("Traité")'),
    ("payments/models.py",
     '"Ignoré"',
     '_("Ignoré")'),
    ("payments/models.py",
     '"Confirmé"',
     '_("Confirmé")'),
    ("payments/models.py",
     '"Non reçu"',
     '_("Non reçu")'),
    ("payments/models.py",
     '"Annulé"',
     '_("Annulé")'),
    ("payments/models.py",
     '"montant",',
     '_("montant"),'),
    ("payments/models.py",
     '"devise", max_length=3, default="XOF"',
     '_("devise"), max_length=3, default="XOF"'),
    ("payments/models.py",
     '"moyen",',
     '_("moyen"),'),
    ("payments/models.py",
     '"statut",',
     '_("statut"),'),
    ("payments/models.py",
     '"recu le",',
     '_("recu le"),'),
    ("payments/models.py",
     '"reference externe",',
     '_("reference externe"),'),
    ("payments/models.py",
     '"note", blank=True',
     '_("note"), blank=True'),
    ("payments/models.py",
     '"mouvement de trésorerie",',
     '_("mouvement de trésorerie"),'),
    ("payments/models.py",
     '"Faux lorsqu\'une caution déjà encaissée est affectée à un loyer."',
     '_("Faux lorsqu\'une caution déjà encaissée est affectée à un loyer.")'),
    ("payments/models.py",
     '"cle d\'idempotence"',
     '_("cle d\'idempotence")'),
    ("payments/models.py",
     '"enregistre par",',
     '_("enregistre par"),'),
    ("payments/models.py",
     'verbose_name = "paiement"',
     'verbose_name = _("paiement")'),
    ("payments/models.py",
     'verbose_name_plural = "paiements"',
     'verbose_name_plural = _("paiements")'),
    ("payments/models.py",
     '"opérateur",',
     '_("opérateur"),'),
    ("payments/models.py",
     '"compte par défaut",',
     '_("compte par défaut"),'),
    ("payments/models.py",
     '"référence",',
     '_("référence"),'),
    ("payments/models.py",
     '"montant demandé",',
     '_("montant demandé"),'),
    ("payments/models.py",
     '"montant reçu",',
     '_("montant reçu"),'),
    ("payments/models.py",
     '"nom du bénéficiaire",',
     '_("nom du bénéficiaire"),'),
    ("payments/models.py",
     '"téléphone du bénéficiaire",',
     '_("téléphone du bénéficiaire"),'),
    ("payments/models.py",
     '"traité le",',
     '_("traité le"),'),
    ("payments/models.py",
     'verbose_name="échéance",',
     'verbose_name=_("échéance"),'),
    ("payments/models.py",
     'verbose_name="compte de réception",',
     'verbose_name=_("compte de réception"),'),
    ("payments/models.py",
     'verbose_name="bailleur bénéficiaire",',
     'verbose_name=_("bailleur bénéficiaire"),'),
    ("payments/models.py",
     'verbose_name="initié par",',
     'verbose_name=_("initié par"),'),
    ("payments/models.py",
     'verbose_name="traité par",',
     'verbose_name=_("traité par"),'),
    ("payments/models.py",
     'verbose_name="paiement créé",',
     'verbose_name=_("paiement créé"),'),
    ("payments/models.py",
     'verbose_name = "événement prestataire de paiement"',
     'verbose_name = _("événement prestataire de paiement")'),
    ("payments/models.py",
     'verbose_name_plural = "événements prestataire de paiement"',
     'verbose_name_plural = _("événements prestataire de paiement")'),
    ("payments/models.py",
     'f"{\' (défaut)\' if self.is_default else \'\'}"',
     'f"{_(\' (défaut)\') if self.is_default else \'\'}"'),

    # ---- payments/api/serializers.py ----
    ("payments/api/serializers.py",
     '"Affecte le paiement à au moins une obligation."',
     '_("Affecte le paiement à au moins une obligation.")'),
    ("payments/api/serializers.py",
     '"Une obligation ne peut apparaître qu\'une fois."',
     '_("Une obligation ne peut apparaître qu\'une fois.")'),
    ("payments/api/serializers.py",
     '"La somme des affectations doit être égale au montant du paiement."',
     '_("La somme des affectations doit être égale au montant du paiement.")'),
    ("payments/api/serializers.py",
     '"À encaisser",',
     '_("À encaisser"),'),
    ("payments/api/serializers.py",
     '"Partiellement détenue",',
     '_("Partiellement détenue"),'),
    ("payments/api/serializers.py",
     '"Détenue",',
     '_("Détenue"),'),
    ("payments/api/serializers.py",
     '"Partiellement clôturée",',
     '_("Partiellement clôturée"),'),
    ("payments/api/serializers.py",
     '"Clôturée",',
     '_("Clôturée"),'),
    ("payments/api/serializers.py",
     '"Le motif de la retenue est obligatoire."',
     '_("Le motif de la retenue est obligatoire.")'),
    ("payments/api/serializers.py",
     '"Sélectionnez un loyer."',
     '_("Sélectionnez un loyer.")'),
    ("payments/api/serializers.py",
     '"Confirmez que le locataire a donné son accord."',
     '_("Confirmez que le locataire a donné son accord.")'),
    ("payments/api/serializers.py",
     '"Indiquez la référence de l\'accord."',
     '_("Indiquez la référence de l\'accord.")'),

    # ---- payments/api/views.py ----
    ("payments/api/views.py",
     '"Utilisez le format AAAA-MM-JJ."',
     '_("Utilisez le format AAAA-MM-JJ.")'),
    ("payments/api/views.py",
     '"Une obligation est introuvable ou inaccessible."',
     '_("Une obligation est introuvable ou inaccessible.")'),

    # ---- payments/api/webhook_views.py ----
    ("payments/api/webhook_views.py",
     '"Le webhook Mobile Money n\'est pas configuré."',
     '_("Le webhook Mobile Money n\'est pas configuré.")'),

    # ---- payments/webhooks.py ----
    ("payments/webhooks.py",
     '"Le secret du webhook Mobile Money n\'est pas configuré."',
     '_("Le secret du webhook Mobile Money n\'est pas configuré.")'),
    ("payments/webhooks.py",
     '"Horodatage invalide."',
     '_("Horodatage invalide.")'),
    ("payments/webhooks.py",
     '"Webhook expiré."',
     '_("Webhook expiré.")'),
    ("payments/webhooks.py",
     '"Signature invalide."',
     '_("Signature invalide.")'),

    # ---- billing ----
    ("billing/api/serializers.py",
     '"Premier mois de loyer au format AAAA-MM."',
     '_("Premier mois de loyer au format AAAA-MM.")'),
    ("billing/api/serializers.py",
     '"Dernier mois de loyer au format AAAA-MM."',
     '_("Dernier mois de loyer au format AAAA-MM.")'),
    ("billing/api/serializers.py",
     '"Indique le premier et le dernier mois de loyer."',
     '_("Indique le premier et le dernier mois de loyer.")'),
    ("billing/api/serializers.py",
     '"Sélectionne la caution ou une période de loyer."',
     '_("Sélectionne la caution ou une période de loyer.")'),
    ("billing/api/views.py",
     '"Utilisez le format AAAA-MM."',
     '_("Utilisez le format AAAA-MM.")'),
    ("billing/models.py",
     '"caution libérée",',
     '_("caution libérée"),'),
    ("billing/models.py",
     '"Montant remboursé, retenu ou affecté. "\n'
     '            "ImmoLib ne conserve pas les fonds."',
     '_("Montant remboursé, retenu ou affecté. "\n'
     '            "ImmoLib ne conserve pas les fonds.")'),
    ("billing/models.py",
     '"La periode doit commencer le premier du mois."',
     '_("La periode doit commencer le premier du mois.")'),
    ("billing/models.py",
     '"Le total doit etre egal au loyer plus les charges."',
     '_("Le total doit etre egal au loyer plus les charges.")'),
    ("billing/models.py",
     '"Une caution ne doit pas être comptabilisée comme un loyer."',
     '_("Une caution ne doit pas être comptabilisée comme un loyer.")'),
    ("billing/models.py",
     '"Seule une caution peut être libérée."',
     '_("Seule une caution peut être libérée.")'),
    ("billing/models.py",
     '"Le total paye ne peut pas depasser le total attendu."',
     '_("Le total paye ne peut pas depasser le total attendu.")'),
    ("billing/services.py",
     '"Un paiement peut couvrir au maximum 120 mois par opération."',
     '_("Un paiement peut couvrir au maximum 120 mois par opération.")'),
    ("billing/apps.py",
     '"Echeances"',
     '_("Echeances")'),

    # ---- documents ----
    ("documents/api/serializers.py",
     '"Le motif est obligatoire pour contester."',
     '_("Le motif est obligatoire pour contester.")'),
    ("documents/api/views.py",
     '"La reponse concerne uniquement un recu de paiement."',
     '_("La reponse concerne uniquement un recu de paiement.")'),
    ("documents/apps.py",
     '"Recus et quittances"',
     '_("Recus et quittances")'),
    ("documents/notifications.py",
     '"La limite doit etre superieure a zero."',
     '_("La limite doit etre superieure a zero.")'),
    ("documents/reminders.py",
     '"Canaux de rappel invalides : "',
     '_("Canaux de rappel invalides : ")'),
    ("documents/services.py",
     '"Paiement annule"',
     '_("Paiement annule")'),
    ("documents/services.py",
     '"L\'obligation n\'est plus entièrement payée"',
     '_("L\'obligation n\'est plus entièrement payée")'),

    # ---- i18n / leases / maintenance ----
    ("i18n/apps.py",
     '"Langues et localisation"',
     '_("Langues et localisation")'),
    ("leases/apps.py",
     '"Locataires et baux"',
     '_("Locataires et baux")'),
    ("leases/services.py",
     '"Utilisez le numéro de téléphone indiqué dans l\'invitation."',
     '_("Utilisez le numéro de téléphone indiqué dans l\'invitation.")'),
    ("leases/services.py",
     '"Utilisez l\'adresse email indiquée dans l\'invitation."',
     '_("Utilisez l\'adresse email indiquée dans l\'invitation.")'),
    ("leases/services.py",
     '"Cette invitation doit d\'abord être validée par le téléphone. Vous pourrez ajouter un email plus tard."',
     '_("Cette invitation doit d\'abord être validée par le téléphone. Vous pourrez ajouter un email plus tard.")'),
    ("leases/services.py",
     '"Vérifiez le téléphone ou l\'email indiqué dans l\'invitation."',
     '_("Vérifiez le téléphone ou l\'email indiqué dans l\'invitation.")'),
    ("leases/services.py",
     '"Ce compte ne correspond pas aux coordonnées de l\'invitation."',
     '_("Ce compte ne correspond pas aux coordonnées de l\'invitation.")'),
    ("maintenance/models.py",
     '"catégorie",',
     '_("catégorie"),'),
    ("maintenance/models.py",
     '"priorité",',
     '_("priorité"),'),
    ("maintenance/models.py",
     '"constaté le",',
     '_("constaté le"),'),
    ("maintenance/models.py",
     '"locataire",',
     '_("locataire"),'),
    ("maintenance/models.py",
     '"Le bien doit correspondre au bail."',
     '_("Le bien doit correspondre au bail.")'),
    ("maintenance/models.py",
     '"Le locataire doit correspondre au bail."',
     '_("Le locataire doit correspondre au bail.")'),
    ("maintenance/services.py",
     'f"Le passage de {incident.get_status_display()} vers ce statut est interdit."',
     '_("Le passage de {status} vers ce statut est interdit.").format(\n'
     '                status=incident.get_status_display()\n'
     '            )'),
    ("maintenance/services.py",
     '"Le locataire peut répondre uniquement après une résolution."',
     '_("Le locataire peut répondre uniquement après une résolution.")'),

    # ---- notifications ----
    ("notifications/adapters.py",
     '"VAPID_PRIVATE_KEY doit être configuré pour le Web Push."',
     '_("VAPID_PRIVATE_KEY doit être configuré pour le Web Push.")'),
    ("notifications/adapters.py",
     '"L\'abonnement push a expiré."',
     '_("L\'abonnement push a expiré.")'),
    ("notifications/models.py",
     'return f"Préférences de {self.user}"',
     'return _("Préférences de {user}").format(user=self.user)'),

    # ---- payments/apps.py, properties ----
    ("payments/apps.py",
     '"Paiements"',
     '_("Paiements")'),
    ("properties/models.py",
     '"téléphone",',
     '_("téléphone"),'),
    ("properties/models.py",
     '"quote-part proposée",',
     '_("quote-part proposée"),'),
    ("properties/models.py",
     '"niveau d\'accès proposé",',
     '_("niveau d\'accès proposé"),'),
    ("properties/services.py",
     '"Seul le propriétaire principal peut gérer les copropriétaires."',
     '_("Seul le propriétaire principal peut gérer les copropriétaires.")'),
    ("properties/services.py",
     '"La somme des quote-parts des copropriétaires doit rester inférieure à 100 %."',
     '_("La somme des quote-parts des copropriétaires doit rester inférieure à 100 %.")'),
    ("properties/services.py",
     '"La gestion des copropriétaires est disponible avec le plan Essentiel."',
     '_("La gestion des copropriétaires est disponible avec le plan Essentiel.")'),
    ("properties/services.py",
     '"Ce compte possède déjà un rôle pour ce bien."',
     '_("Ce compte possède déjà un rôle pour ce bien.")'),
    ("properties/services.py",
     '"Une invitation est déjà en attente pour ce numéro."',
     '_("Une invitation est déjà en attente pour ce numéro.")'),

    # ---- sms / whatsapp ----
    ("sms/phones.py",
     '"Numero invalide : utilisez le format ivoirien +2250700000000."',
     '_("Numero invalide : utilisez le format ivoirien +2250700000000.")'),
    ("whatsapp/models.py",
     '"numéro de l\'expéditeur",',
     '_("numéro de l\'expéditeur"),'),
    ("whatsapp/provider.py",
     '"WHATSAPP_ACCESS_TOKEN et WHATSAPP_PHONE_NUMBER_ID doivent être configurés."',
     '_("WHATSAPP_ACCESS_TOKEN et WHATSAPP_PHONE_NUMBER_ID doivent être configurés.")'),
]

failures = []
for path, old, new, *expected in REPLACEMENTS:
    expected_count = expected[0] if expected else 1
    file_path = BASE / path
    text = file_path.read_text(encoding="utf-8")
    count = text.count(old)
    if count != expected_count:
        failures.append(f"{path}: attendu {expected_count}, trouve {count}: {old[:70]}")
        continue
    text = text.replace(old, new)
    file_path.write_text(text, encoding="utf-8")

print(f"OK: {len(REPLACEMENTS) - len(failures)} / {len(REPLACEMENTS)}")
for f in failures:
    print("ECHEC:", f)
