# Generated by Django 5.2.16 on 2026-07-21 11:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('PRIMARY', 'Proprietaire principal'), ('CO_OWNER', 'Coproprietaire')], max_length=20, verbose_name='role')),
                ('access_level', models.CharField(choices=[('ACTIVE', 'Actif'), ('OBSERVER', 'Observateur')], default='OBSERVER', max_length=20, verbose_name="niveau d'acces")),
                ('ownership_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100)], verbose_name='quote-part')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ownerships', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'propriete',
                'verbose_name_plural': 'proprietes',
                'ordering': ['property', 'role', 'user'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('property_type', models.CharField(choices=[('HOUSE', 'Maison')], default='HOUSE', editable=False, max_length=20, verbose_name='type de bien')),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('address', models.CharField(max_length=255, verbose_name='adresse')),
                ('commune', models.CharField(blank=True, max_length=120, verbose_name='commune')),
                ('city', models.CharField(max_length=120, verbose_name='ville')),
                ('landmark', models.CharField(blank=True, max_length=255, verbose_name='repere')),
                ('status', models.CharField(choices=[('VACANT', 'Vacante'), ('OCCUPIED', 'Occupee'), ('UNAVAILABLE', 'Indisponible')], default='VACANT', max_length=20, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owners', models.ManyToManyField(related_name='owned_properties', through='properties.Ownership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'maison',
                'verbose_name_plural': 'maisons',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='ownership',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='properties.property', verbose_name='maison'),
        ),
        migrations.AddConstraint(
            model_name='ownership',
            constraint=models.UniqueConstraint(fields=('property', 'user'), name='one_ownership_per_user_and_property'),
        ),
        migrations.AddConstraint(
            model_name='ownership',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'PRIMARY')), fields=('property',), name='one_primary_owner_per_property'),
        ),
    ]
