# Generated by Django 5.2.16 on 2026-07-21 14:05

import django.core.validators
import django.db.models.deletion
import modules.properties.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_ownership_ownership_percentage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoOwnerInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20, verbose_name='téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('ownership_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('99.99'))], verbose_name='quote-part proposée')),
                ('access_level', models.CharField(choices=[('ACTIVE', 'Actif'), ('OBSERVER', 'Observateur')], default='OBSERVER', max_length=20, verbose_name="niveau d'accès proposé")),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('ACCEPTED', 'Acceptée'), ('REVOKED', 'Révoquée')], default='PENDING', max_length=16, verbose_name='statut')),
                ('expires_at', models.DateTimeField(default=modules.properties.models.default_invitation_expiry)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_co_owner_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_co_owner_invitations', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_owner_invitations', to='properties.property', verbose_name='maison')),
            ],
            options={
                'verbose_name': 'invitation de copropriétaire',
                'verbose_name_plural': 'invitations de copropriétaires',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('property', 'phone'), name='one_pending_coowner_invitation_per_phone_and_property')],
            },
        ),
    ]
