# Generated by Django 5.2.16 on 2026-07-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_backfill_primary_ownership_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coownerinvitation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('ACCEPTED', 'Acceptée'), ('REVOKED', 'Révoquée'), ('EXPIRED', 'Expirée')], default='PENDING', max_length=16, verbose_name='statut'),
        ),
    ]
