# Generated by Django 5.2.16 on 2026-07-24 12:51

import modules.accounts.phones
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_coownerinvitation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coownerinvitation',
            name='phone',
            field=models.CharField(max_length=20, validators=[modules.accounts.phones.validate_e164], verbose_name='téléphone'),
        ),
    ]
