# Generated by Django 5.2.17 on 2026-08-11 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_coownerinvitation_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['name'], 'verbose_name': 'bien', 'verbose_name_plural': 'biens'},
        ),
        migrations.AlterField(
            model_name='coownerinvitation',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_owner_invitations', to='properties.property', verbose_name='bien'),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='properties.property', verbose_name='bien'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('HOUSE', 'Maison'), ('APARTMENT', 'Appartement'), ('LAND', 'Terrain'), ('COMMERCIAL', 'Local commercial')], default='HOUSE', max_length=20, verbose_name='type de bien'),
        ),
    ]
