# Generated by Django 5.2.16 on 2026-07-21 12:05

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField(verbose_name='debut de periode')),
                ('period_end', models.DateField(verbose_name='fin de periode')),
                ('due_date', models.DateField(verbose_name='date limite')),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='loyer')),
                ('charges_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='charges')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='total attendu')),
                ('currency', models.CharField(default='XOF', max_length=3, verbose_name='devise')),
                ('status', models.CharField(choices=[('UPCOMING', 'A venir'), ('DUE', 'A payer'), ('PARTIALLY_PAID', 'Partiellement payee'), ('PAID', 'Payee'), ('OVERDUE', 'En retard'), ('DISPUTED', 'Contestee'), ('CANCELLED', 'Annulee')], default='UPCOMING', max_length=24, verbose_name='statut')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rent_charges', to='leases.lease', verbose_name='bail')),
            ],
            options={
                'verbose_name': 'echeance de loyer',
                'verbose_name_plural': 'echeances de loyer',
                'ordering': ['-period_start', 'lease'],
                'constraints': [models.UniqueConstraint(fields=('lease', 'period_start'), name='one_rent_charge_per_lease_and_period'), models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='rent_charge_period_end_after_start'), models.CheckConstraint(condition=models.Q(('due_date__gte', models.F('period_start')), ('due_date__lte', models.F('period_end'))), name='rent_charge_due_date_inside_period'), models.CheckConstraint(condition=models.Q(('amount_due__gt', 0)), name='rent_charge_amount_due_positive')],
            },
        ),
    ]
