# Generated by Django 5.2.16 on 2026-07-21 12:13

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('leases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentcharge',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='total paye'),
        ),
        migrations.AddConstraint(
            model_name='rentcharge',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paid__gte', 0), ('amount_paid__lte', models.F('amount_due'))), name='rent_charge_paid_between_zero_and_due'),
        ),
    ]
