# Generated by Django 5.2.16 on 2026-07-24 12:24

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_rentcharge_amount_paid_and_more'),
        ('leases', '0002_tenantinvitation_tenantinvitationshareevent_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rentcharge',
            name='one_rent_charge_per_lease_and_period',
        ),
        migrations.RemoveConstraint(
            model_name='rentcharge',
            name='rent_charge_due_date_inside_period',
        ),
        migrations.AddField(
            model_name='rentcharge',
            name='charge_type',
            field=models.CharField(choices=[('RENT', 'Loyer'), ('SECURITY_DEPOSIT', 'Caution')], default='RENT', max_length=24, verbose_name="type d'obligation"),
        ),
        migrations.AlterField(
            model_name='rentcharge',
            name='rent_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='loyer'),
        ),
        migrations.AddConstraint(
            model_name='rentcharge',
            constraint=models.UniqueConstraint(fields=('lease', 'charge_type', 'period_start'), name='one_obligation_per_lease_type_period'),
        ),
        migrations.AddConstraint(
            model_name='rentcharge',
            constraint=models.UniqueConstraint(condition=models.Q(('charge_type', 'SECURITY_DEPOSIT')), fields=('lease',), name='one_security_deposit_obligation_per_lease'),
        ),
        migrations.AddConstraint(
            model_name='rentcharge',
            constraint=models.CheckConstraint(condition=models.Q(('due_date__gte', models.F('period_start')), ('due_date__lte', models.F('period_end'))), name='obligation_due_date_inside_period'),
        ),
    ]
