# Generated by Django 5.2.16 on 2026-07-24 12:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_remove_rentcharge_one_rent_charge_per_lease_and_period_and_more'),
        ('leases', '0003_alter_tenant_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentcharge',
            name='amount_released',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Montant remboursé, retenu ou affecté. ImmoLib ne conserve pas les fonds.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='caution libérée'),
        ),
        migrations.AddIndex(
            model_name='rentcharge',
            index=models.Index(fields=['charge_type', 'status', 'period_start'], name='obligation_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='rentcharge',
            index=models.Index(fields=['lease', 'charge_type', 'status'], name='obligation_lease_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='rentcharge',
            constraint=models.CheckConstraint(condition=models.Q(('amount_released__gte', 0), ('amount_released__lte', models.F('amount_paid'))), name='deposit_released_between_zero_and_paid'),
        ),
    ]
